version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app

  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./front:/app
