version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ${DEFAULT_FILE}
    ports:
      - "80:80"
  api:
    build:
      context: ./backend
      dockerfile: ${DEFAULT_FILE}
    volumes:
      - /app/node_modules
      - ./backend:/app

  client:
    build:
      context: ./front
      dockerfile: ${CLIENT_FILE}
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./front:/app
